### ISSUE TITLE
ImportError: DLL load failed while importing vtkimporter:

### ISSUE THREAD

**Issue by Myiced-ZJU** [EPhysLab-UVigo/VisualSPHysics#15]
I select the downloaded or compiled ZIP file VisualSPHysics.zip in Blender, But I can not enable the checkbox with “Object: VisualSPHysics Blender Addon”  it shows that ImportError: DLL load failed while importing vtkimporter.

**Comment by djsnarf** [comment]
Hi,

I am experiencing exactly the same issue, any clues on how to fix it?

Thanks,

**Comment by lixiaole2017** [comment]
The python version is inconsistent，need to rebuild

**Comment by djsnarf** [comment]
> The python version is inconsistent，need to rebuild

Hi, 

Not sure what you mean by rebuild but I have tried everything, the exact error is this one

Traceback (most recent call last):
  File "C:\Utils\blender-2.93.1-windows-x64\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\VisualSPHysics.py", line 30, in <module>
    import vtkimporter
ImportError: DLL load failed while importing vtkimporter: The specified module could not be found.

**Comment by lixiaole2017** [comment]
The new blender corresponds to python version 3.9, but VisualSPHysics relies on python version 3.7。VisualSPHysics needs to be recompiled into a library on python 3.9




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Sunday, Jun 27, 2021 6:42 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [EPhysLab-UVigo/VisualSPHysics] ImportError: DLL load failed while importing vtkimporter: (#15)





  
The python version is inconsistent，need to rebuild
  
Hi,
 
Not sure what you mean by rebuild but I have tried everything, the exact error is this one
 
Traceback (most recent call last):
 File "C:\Utils\blender-2.93.1-windows-x64\2.93\scripts\modules\addon_utils.py", line 351, in enable
 mod = import(module_name)
 File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\VisualSPHysics.py", line 30, in 
 import vtkimporter
 ImportError: DLL load failed while importing vtkimporter: The specified module could not be found.

**Comment by djsnarf** [comment]
> The new blender corresponds to python version 3.9, but VisualSPHysics relies on python version 3.7。VisualSPHysics needs to be recompiled into a library on python 3.9

I see, ok no clue how to do that. 

Many thanks for taking your time to respond, now I know I cannot fix it myself.

Cheers,

**Comment by Myiced-ZJU** [comment]
> The new blender corresponds to python version 3.9, but VisualSPHysics relies on python version 3.7。VisualSPHysics needs to be recompiled into a library on python 3.9
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Send time:&nbsp;Sunday, Jun 27, 2021 6:42 AM ***@***.***&gt;; ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [EPhysLab-UVigo/VisualSPHysics] ImportError: DLL load failed while importing vtkimporter: (#15) The python version is inconsistent，need to rebuild Hi, Not sure what you mean by rebuild but I have tried everything, the exact error is this one Traceback (most recent call last): File "C:\Utils\blender-2.93.1-windows-x64\2.93\scripts\modules\addon_utils.py", line 351, in enable mod = import(module_name) File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\VisualSPHysics.py", line 30, in import vtkimporter ImportError: DLL load failed while importing vtkimporter: The specified module could not be found. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you , it works

**Comment by Myiced-ZJU** [comment]
> > The new blender corresponds to python version 3.9, but VisualSPHysics relies on python version 3.7。VisualSPHysics needs to be recompiled into a library on python 3.9
> 
> I see, ok no clue how to do that.
> 
> Many thanks for taking your time to respond, now I know I cannot fix it myself.
> 
> Cheers,

Hi , I tried blender 2.9.1 with python version 3.7 ,it works now

**Comment by djsnarf** [comment]
> Dear all
> FolIowing the install wiki, I select the downloaded or compiled ZIP file VisualSPHysics.zip in Blender, But I can not enable the checkbox with “Object: VisualSPHysics Blender Addon” it shows that "ImportError: DLL load failed while importing vtkimporter."
> 
> os : windows 10
> blender version : 2.93.0
> with Visual studio 2017
> 
> thanks a lot

My friend, just download blender previos version 2.83 from here and that fixes it:

https://download.blender.org/release/

Regards,

**Comment by Rodland** [comment]
Dear all, 

I've uploaded a new minor release 1.2.1 compiled using Python 3.9. This now should work with Blender 2.93.

Regards.

**Comment by djsnarf** [comment]
> Dear all,
> 
> I've uploaded a new minor release 1.2.1 compiled using Python 3.9. This now should work with Blender 2.93.
> 
> Regards.

Nice one! thank you.

**Comment by djack73** [comment]
hello,
I've downloaded the 1.2.1 version of the addon but even if Blender says that it has been installed nothing appears in the addon tab. Any idea where's the problem ?
